"""Optional grounded decision helpers for Scarf workflows."""

from .biological_interpretation import (
    BiologicalContext,
    BiologicalInterpretationAgent,
    BiologicalInterpretationReport,
)
from .experimental_context.characterization import characterize_covariates
from .experimental_context.contracts import CovariateCharacterization
from .data_enrichment.characterization import (
    FeatureCharacterization,
    characterize_features,
)
from .config import AgentRunConfig
from . import _deps as _deps
from .config.agent_exec import run_agent, run_agent_sync
from .data_enrichment import (
    DataEnrichmentAgent,
    DataEnrichmentContext,
    DataEnrichmentReport,
    StudyContextSummary,
)
from .decisions.selection import DecisionValidationError, decide
from .decisions.kernel import (
    DecisionEvidence,
    DecisionOption,
    DecisionRecord,
    DecisionSelection,
    DecisionSpec,
    DecisionWorkflowRun,
    DeterministicDecisionAuditor,
    EvidenceBundle,
    PendingDecision,
    ProtectedVariableEffect,
    RevisionRequest,
    VerificationCheck,
    VerificationRecord,
)
from .experimental_context import (
    CellQcPlan,
    ExperimentalContextAgent,
    ExperimentalContextResult,
    NamedArtifactSource,
)
from .ingest import (
    DatasetManifest,
    DatasetManifestDecision,
    IngestResult,
    detect_format,
    ingest,
    inspect_h5ad_manifest,
)
from .orchestrator import (
    AgentOrchestrator,
    AssayPreprocessingPlan,
    AutomatedPreprocessingPlan,
    AutomatedWorkflowConfig,
    AutomatedWorkflowRequest,
    AutomatedWorkflowResult,
    AutomatedWorkflowResumeRequest,
    FinalAnalysisHandoff,
    NativeAnalysisHandoff,
    PreprocessedAssayHandoff,
    WorkflowNeedsInput,
    WorkflowQuestion,
    WorkflowStageAttempt,
    WorkflowStageLink,
)
from .parameter_tuning import (
    FinalGraphSelection,
    IntegrationCandidateEvaluation,
    IntegrationMetrics,
    ParameterCandidate,
    ParameterSearchPlan,
    ParameterTuningAgent,
    ParameterTuningAssayInput,
    ParameterTuningReport,
    get_default_parameter_candidates,
    tune_parameters,
)
from .persistence import (
    AgentInvocation,
    AgentName,
    AgentPersistenceTarget,
    AgentReport,
    AgentReportLink,
    AgentReportRecord,
    AgentReportReference,
    AgentReportType,
    AgentTerminalStatus,
    AgentWorkflowRun,
    AgentWorkflowStatus,
    create_agent_workflow,
    finalize_agent_workflow,
    list_agent_reports,
    list_agent_workflows,
    load_agent_record,
    load_agent_report,
    load_agent_workflow,
    save_agent_report,
)
from .report import generate_agent_report
from .runtime import check_runtime, load_env
from .experimental_context.study import StudyContract
from .types import (
    BatchSafetyEvidence,
    Decision,
    EvidenceItem,
    ExperimentalBiologyHandoff,
    ExperimentalTuningHandoff,
    NeedsInput,
    StageResult,
    StageStatus,
    TuningBiologyHandoff,
)

__all__ = [
    "AgentInvocation",
    "AgentOrchestrator",
    "AgentRunConfig",
    "AgentName",
    "AgentPersistenceTarget",
    "AgentReport",
    "AgentReportLink",
    "AgentReportRecord",
    "AgentReportReference",
    "AgentReportType",
    "AgentTerminalStatus",
    "AgentWorkflowRun",
    "AgentWorkflowStatus",
    "AssayPreprocessingPlan",
    "AutomatedPreprocessingPlan",
    "AutomatedWorkflowConfig",
    "AutomatedWorkflowRequest",
    "AutomatedWorkflowResult",
    "AutomatedWorkflowResumeRequest",
    "BatchSafetyEvidence",
    "BiologicalContext",
    "BiologicalInterpretationAgent",
    "BiologicalInterpretationReport",
    "CellQcPlan",
    "CovariateCharacterization",
    "DataEnrichmentAgent",
    "DataEnrichmentContext",
    "DataEnrichmentReport",
    "Decision",
    "DecisionEvidence",
    "DecisionOption",
    "DecisionRecord",
    "DecisionSelection",
    "DecisionSpec",
    "DecisionWorkflowRun",
    "DecisionValidationError",
    "DeterministicDecisionAuditor",
    "DatasetManifest",
    "DatasetManifestDecision",
    "EvidenceItem",
    "EvidenceBundle",
    "ExperimentalBiologyHandoff",
    "ExperimentalContextAgent",
    "ExperimentalContextResult",
    "ExperimentalTuningHandoff",
    "FinalAnalysisHandoff",
    "FinalGraphSelection",
    "FeatureCharacterization",
    "IngestResult",
    "IntegrationCandidateEvaluation",
    "IntegrationMetrics",
    "NativeAnalysisHandoff",
    "NamedArtifactSource",
    "NeedsInput",
    "PendingDecision",
    "ParameterCandidate",
    "ParameterSearchPlan",
    "ParameterTuningAssayInput",
    "ParameterTuningAgent",
    "ParameterTuningReport",
    "PreprocessedAssayHandoff",
    "ProtectedVariableEffect",
    "RevisionRequest",
    "StageResult",
    "StageStatus",
    "StudyContextSummary",
    "StudyContract",
    "TuningBiologyHandoff",
    "WorkflowNeedsInput",
    "WorkflowQuestion",
    "WorkflowStageAttempt",
    "WorkflowStageLink",
    "VerificationCheck",
    "VerificationRecord",
    "characterize_covariates",
    "characterize_features",
    "check_runtime",
    "create_agent_workflow",
    "decide",
    "detect_format",
    "get_default_parameter_candidates",
    "generate_agent_report",
    "ingest",
    "inspect_h5ad_manifest",
    "load_env",
    "finalize_agent_workflow",
    "list_agent_reports",
    "list_agent_workflows",
    "load_agent_record",
    "load_agent_report",
    "load_agent_workflow",
    "run_agent",
    "run_agent_sync",
    "save_agent_report",
    "tune_parameters",
]
